### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by jeffrycopps** [relwell/BeerSite#1]
Which version of Python are you using? 
I tried with 2.7. 
Error @ total = response.get('total', 0)

**Comment by relwell** [comment]
Can you paste the error?

**Comment by jeffrycopps** [comment]
Traceback (most recent call last):
  File "importBeer.py", line 8, in <module>
    total = response.get('total', 0)
AttributeError: 'str' object has no attribute 'get'

**Comment by relwell** [comment]
It looks like the Open Beer Database is kaput. Unfortunately, I can't do anything about that.

**Comment by jeffrycopps** [comment]
Oh.. Appreciate your response. Thanks.
